services:
   backend:
     build:
       context: .
       dockerfile: Dockerfile
     container_name: backend
     command: >
       sh -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
     volumes:
       - .:/app
     ports:
       - "8000:8000"
     env_file:
       - .env
     depends_on:
       - db
       - redis

   db:
     image: postgres:15
     container_name: postgres_db
     environment:
       - USER=${USER}
       - PASSWORD=${PASSWORD}
       - HOST=${HOST}
     volumes:
       - postgres_data:/var/lib/postgresql/data
     ports:
       - "5432:5432"

   redis:
     image: redis:7
     container_name: redis
     command: redis-server --requirepass ${REDIS_URL}
     ports:
       - "6379:6379"

   celery:
     build:
       context: .
       dockerfile: Dockerfile
     container_name: celery_worker
     command: celery -A myproject worker -l info
     volumes:
       - .:/app
     env_file:
       - .env
     depends_on:
       - backend
       - redis

   celery-beat:
     build:
       context: .
       dockerfile: Dockerfile
     container_name: celery_beat
     command: celery -A myproject beat -l info
     volumes:
       - .:/app
     env_file:
       - .env
     depends_on:
       - backend
       - redis

volumes:
   postgres_data:
